/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "superApi",
            "endpoint": "https://dg801j76g8.execute-api.sa-east-1.amazonaws.com/staging",
            "region": "sa-east-1"
        },
        {
            "name": "APIsuper",
            "endpoint": "https://2lfxx71eca.execute-api.sa-east-1.amazonaws.com/staging",
            "region": "sa-east-1"
        }
    ]
};


export default awsmobile;
